_welcome:
    pattern:  /
    defaults: { _controller: AEloginBundle:Default:index }
    
ae_discipular:
    resource: "@AEDiscipularBundle/Resources/config/routing.yml"
    prefix:   /discipular/

ae_consolidar:
    resource: "@AEConsolidarBundle/Resources/config/routing.yml"
    prefix:   /con/

ae_ganar:
    resource: "@AEGanarBundle/Resources/config/routing.yml"
    prefix:   /ganar/

ae_enviar:
    resource: "@AEEnviarBundle/Resources/config/routing.yml"
    prefix:   /enviar/

ae_administrar:
    resource: "@AEAdministrarBundle/Resources/config/routing.yml"
    prefix:   /

a_elogin:
    resource: "@AEloginBundle/Resources/config/routing.yml"
    prefix:   /

ae_servicios:
    resource: "@AEServiciosBundle/Resources/config/routing.yml"
    prefix:   /

ae_data:
    resource: "@AEDataBundle/Resources/config/routing.yml"
    prefix:   /

#clm_data:
 #   resource: "@CLMDataBundle/Resources/config/routing.yml"
  #  prefix:   /
    
    
_security_logout:
    pattern:  /salir


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
