ae_administrar_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEAdministrarBundle:Default:index }
administrar_iglesia:
    pattern: /iglesias
    defaults: {_controller: AEAdministrarBundle:Iglesia:igle}
    
administrar_addigle:
    pattern: /regigle
    defaults: {_controller: AEAdministrarBundle:Iglesia:addigle}
    requirements:
          _method: POST
    
administrar_modiglesia:
  pattern: /modiglesia
  defaults: {_controller: AEAdministrarBundle:Iglesia:modiglesia}
  
administrar_updateiglesia:
  pattern: /updateiglesia
  defaults: {_controller: AEAdministrarBundle:Iglesia:updateiglesia}
  requirements:
      _method: POST

administrar_permisos:
  pattern: /permisos
  defaults: {_controller: AEAdministrarBundle:Permiso:permiso}
 
administrar_reg_permisos:
  pattern: /regpermi
  defaults: {_controller: AEAdministrarBundle:Permiso:regpermiso}
  requirements:
    _method: POST
  
administrar_mod_permisos:
  pattern: /modpermisos
  defaults: {_controller: AEAdministrarBundle:Permiso:modpermiso}
  
administrar_mod_permiso_update:
  pattern: /modpermisoupdate
  defaults: {_controller: AEAdministrarBundle:Permiso:modpermisoupdate}
  requirements:
    _method: POST
  
administrar_red:
  pattern: /red
  defaults: {_controller: AEAdministrarBundle:Red:red}
  
administrar_addred:
  pattern: /regred
  defaults: {_controller: AEAdministrarBundle:Red:addred}
  requirements:
    _method: POST
    
administrar_asignarlider:
  pattern: /asignar_lider_red
  defaults: {_controller: AEAdministrarBundle:Red:asignared}
  
administrar_add_asignar_lider:
  pattern: /add_lider_red
  defaults: {_controller: AEAdministrarBundle:Red:addasignarlider}
  
  
administrar_lista_pastor_asociado:
  pattern: /lista_pastor_asociado
  defaults: {_controller: AEAdministrarBundle:Default:lista_pastor_asociado}
  
administrar_lista_pastor_ejecutivo:
  pattern: /lista_pastor_ejecutivo
  defaults: {_controller: AEAdministrarBundle:Default:lista_pastor_ejecutivo}
  
administrar_lista_lider_red:
  pattern: /lista_lider_red
  defaults: {_controller: AEAdministrarBundle:Default:lista_lider_red}
  
administrar_lista_misionero:
  pattern: /lista_misionero
  defaults: {_controller: AEAdministrarBundle:Default:lista_misionero}
  
administrar_lista_miembros:
  pattern: /lista_miembros
  defaults: {_controller: AEAdministrarBundle:Default:lista_miembros}
  
administrar_lista_miembros_all:
  pattern: /lista_miembros_all
  defaults: {_controller: AEAdministrarBundle:Default:lista_miembros_all}
  
administrar_lista_redes:
  pattern: /lista_redes
  defaults: {_controller: AEAdministrarBundle:Default:lista_redes}
  
  
administrar_lista_usuario:
  pattern: /lista_usuarios
  defaults: {_controller: AEAdministrarBundle:Default:lista_usuarios}
 
  
administrar_lista_redes_modificar_vista:
  pattern: /lista_redes_modificar_vista/{id}
  defaults: {_controller: AEAdministrarBundle:Default:lista_redes_modificar_vista}
  
administrar_lista_redes_modificar_update:
  pattern: /lista_redes_modificar
  defaults: {_controller: AEAdministrarBundle:Default:lista_redes_modificar}
  requirements:
    _method: POST
  
administrar_lista_redes_eliminar:
  pattern: /lista_redes_eliminar
  defaults: {_controller: AEAdministrarBundle:Default:lista_redes_eliminar}
  requirements:
    _method: POST
    
administrar_clase:
  pattern: /clase
  defaults: {_controller: AEAdministrarBundle:Default:clase}
  
  
administrar_clase_registrar:
  pattern: /clase_reg
  defaults: {_controller: AEAdministrarBundle:Default:clase_reg}
  requirements:
    _method: POST
    
administrar_tema_leche:
  pattern: /temas_leche
  defaults: {_controller: AEAdministrarBundle:Default:temas_leche}
  requirements:
    _method: POST
    
administrar_file_leche:
  pattern: /file_leche
  defaults: {_controller: AEAdministrarBundle:Default:file_leche}
     
tools_consolidar_routing:
    resource: "@AEAdministrarBundle/Resources/config/Tools_routing.yml"
    
administrar_administrar_evento:
  pattern: /administrar_evento
  defaults: {_controller: AEAdministrarBundle:AdministrarEvento:index}
  
administrar_ver_eventos:
  pattern: /ver_eventos
  defaults: {_controller: AEAdministrarBundle:AdministrarEvento:VerEventos}
  
administrar_registrar_evento:
  pattern: /registrar_evento
  defaults: {_controller: AEAdministrarBundle:AdministrarEvento:RegistrarEvento}
  requirements:
    _method: POST

administrar_asistencia_evento:
  pattern: /asistencia_evento
  defaults: {_controller: AEAdministrarBundle:AdministrarEvento:AsistenciaEvento}
  requirements:
    _method: POST
    
administrar_eliminar_evento:
  pattern: /eliminar_evento
  defaults: {_controller: AEAdministrarBundle:AdministrarEvento:EliminarEvento}
  requirements:
    _method: POST
    
administrar_registrar_persona_evento:
  pattern: /registrar_persona_evento
  defaults: {_controller: AEAdministrarBundle:AdministrarEvento:RegistrarPersonaEvento}
  requirements:
    _method: POST
    
    
administrar_roles:
  pattern: /admin_roles
  defaults: {_controller: AEAdministrarBundle:Roles:vista}
  
administrar_crear_usuarios:
  pattern: /admincrearusuarios
  defaults: {_controller: AEAdministrarBundle:Default:admincrearusuarios}
  requirements:
    _method: POST
    
administrar_lider12:
  pattern: /admin_lider12
  defaults: {_controller: AEAdministrarBundle:Lider:adminlider12}
  
administrar_lider12_up:
  pattern: /admin_lider12up
  defaults: {_controller: AEAdministrarBundle:Lider:adminlider12up}
  requirements: 
    _method: POST
   
administrar_lider144:
  pattern: /admin_lider144
  defaults: {_controller: AEAdministrarBundle:Lider:adminlider144}
  
administrar_lider144up:
  pattern: /admin_lider144up
  defaults: {_controller: AEAdministrarBundle:Lider:adminlider144up}
  requirements:
    _method: POST
    
administrar_lider1728:
  pattern: /admin_lider1728
  defaults: {_controller: AEAdministrarBundle:Lider:adminlider1728}
  
administrar_lider1728up:
  pattern: /admin_lider1728up
  defaults: {_controller: AEAdministrarBundle:Lider:adminlider1728up}
  requirements:
    _method: POST
    
administrar_asistencia_culto:
  pattern: /asistencia_culto
  defaults: {_controller: AEAdministrarBundle:Lider:asistencia_culto}
  
administrar_asistencia_culto_up:
  pattern: /asistencia_culto_up
  defaults: {_controller: AEAdministrarBundle:Lider:asistencia_culto_up}
  requirements:
    _method: POST
    
administrar_asistencia_lista:
  pattern: /asistencia_lista
  defaults: {_controller: AEAdministrarBundle:Lider:asistencia_lista}
  
administrar_registro_ropa_vista:
  pattern: /registro_ropa_vista
  defaults: {_controller: AEAdministrarBundle:Ropa:vista_ropa}
  
administrar_registro_ropa_vista_up:
  pattern: /registro_ropa_vista_up
  defaults: {_controller: AEAdministrarBundle:Ropa:registro_ropa_up}
  
administrar_informe_ropa_red:
  pattern: /informe_ropa_red
  defaults: {_controller: AEAdministrarBundle:Ropa:informeropared}
  
administrar_informe_ropa_tipo:
  pattern: /informe_ropa_tipo
  defaults: {_controller: AEAdministrarBundle:Ropa:informeropatipo}
  
administrar_informe_ropa:
  pattern: /informe_ropa
  defaults: {_controller: AEAdministrarBundle:Ropa:informeropa}
  
  
administrar_cambiar_usuario:
  pattern: /cambiar_clave
  defaults: {_controller: AEAdministrarBundle:User:cambiarusuario}
  
administrar_cambiar_usuario_up:
  pattern: /cambiar_clave_up
  defaults: {_controller: AEAdministrarBundle:User:cambiarusuario_up}
  requirements:
    _method: POST
    
administrar_estado_usuario_up:
  pattern: /estado_usuario_up
  defaults: {_controller: AEAdministrarBundle:User:estadousuario_up}
  requirements:
    _method: POST
        
administrar_check_user:
  pattern: /check_user/{user}
  defaults: {_controller: AEAdministrarBundle:User:check_user}
  requirements:
    _method: POST